- type: gameMapPool
  id: StarcupDefaultMapPool
  maps:
  - Amber
  - Bagel
  - Box
  - Byoin  # starcup: ported from delta-v
  - Convex
  #- Core
  - Elkridge
  - Fland
  - Glacier # starcup: ported from Delta-V. enabled.
  #- Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omegastarcup
  - Packed
  - Plasma
  - Reach
  - Salternstarcup # starcup: wasn't on the list for some reason? enabled.
  #- Train
