name: "Close Stale PRs"

on:
  workflow_dispatch:
  schedule:
   - cron: '0 10 * * *'

jobs:
  close-stale:
    if: github.repository == "teamstarcup/starcup"
    runs-on: ubuntu-latest
    steps:
      - name: "Close Stale PRs"
        uses: actions/stale@v9.1.0
        with:
          days-before-pr-stale: 14
          days-before-pr-close: 14
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-pr-message: 'This pull request has been marked as stale because it has been inactive for more than 14 days. Please update this pull request or it will be automatically closed in 14 days.'
          close-pr-message: 'We close pull requests that have been inactive for four weeks in an attempt to keep our backlog from piling up. Please update this pull request or request a review to bring this back up with our team.'
          stale-pr-label: stale
